export const headphonesArray = [
  {
    img: '../../assets/Apple BYZ S852I.png',
    title: 'Apple BYZ S852I',
    price: 2927,
    oldPrice: 3527,
    rate: 4.7,
    isWireless: false,
  },
  {
    img: '../../assets/Apple EarPods.png',
    title: 'Apple EarPods',
    price: 2327,
    oldPrice: null,
    rate: 4.5,
    isWireless: false,
  },
  {
    img: '../../assets/Apple EarPods(packed).png',
    title: 'Apple EarPods',
    price: 2327,
    oldPrice: null,
    rate: 4.5,
    isWireless: false,
  },
  {
    img: '../../assets/Apple BYZ S852I.png',
    title: 'Apple BYZ S852I',
    price: 2927,
    oldPrice: null,
    rate: 4.7,
    isWireless: false,
  },
  {
    img: '../../assets/Apple EarPods.png',
    title: 'Apple EarPods',
    price: 2327,
    oldPrice: null,
    rate: 4.5,
    isWireless: false,
  },
  {
    img: '../../assets/Apple EarPods(packed).png',
    title: 'Apple EarPods',
    price: 2327,
    oldPrice: null,
    rate: 4.5,
    isWireless: false,
  },
  {
    img: '../../assets/Apple AirPods.png',
    title: 'Apple EarPods',
    price: 9527,
    oldPrice: null,
    rate: 4.7,
    isWireless: true,
  },
  {
    img: '../../assets/GERLAX GH-04.png',
    title: 'GERLAX GH-04',
    price: 6527,
    oldPrice: null,
    rate: 4.7,
    isWireless: true,
  },
  {
    img: '../../assets/BOROFONE BO4.png',
    title: 'BOROFONE BO4',
    price: 7527,
    oldPrice: null,
    rate: 4.7,
    isWireless: true,
  },
];
